const fs=require('fs'),vm=require('vm'),assert=require('assert');
const all=[], ids={};
class El{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.style={};this.dataset={};this.children=[];this.events={};this.textContent='';this.value='';this.options=[];const c=new Set();this.classList={add:x=>c.add(x),remove:x=>c.delete(x),toggle:(x,f)=>{f??=!c.has(x);f?c.add(x):c.delete(x)},contains:x=>c.has(x)};}
 addEventListener(k,f){(this.events[k]??=[]).push(f)}
 trigger(k){for(const f of this.events[k]||[])f({target:this,preventDefault(){},pointerId:1})}
 append(...xs){this.children.push(...xs);for(const x of xs){x.parent=this;if(this.tagName==='SELECT')this.options.push(...(x.tagName==='OPTION'?[x]:x.children));}}
 replaceChildren(...x){this.children=[];this.options=[];this.append(...x)}
 setAttribute(k,v){this[k]=v}setPointerCapture(){} getBoundingClientRect(){return {left:0,top:0,width:136,height:136}}
 set innerHTML(t){this.html=t;if(this.tagName==='SELECT'){this.options=[...t.matchAll(/<option value="([^"]+)"[^>]*>(.*?)<\/option>/g)].map(m=>({value:m[1],textContent:m[2]}));this.value=this.options[0]?.value||'';}}
 get innerHTML(){return this.html||''}
}
for(const d of JSON.parse(fs.readFileSync(require('path').join(__dirname,'dom-fixture.json')))){const e=new El(d.tag);Object.assign(e,{id:d.id,dataset:d.dataset,textContent:d.text,value:d.value,options:d.options});if(d.options.length)e.value=(d.options.find(o=>o.selected)||d.options[0]).value;all.push(e);if(d.id)ids[d.id]=e;}
for(const id of ['keyBindingRows','keyBindingStatus','keyboardHelp','keyboardSettings','resetKeyBindings','commentaryProfileSelect','commentaryVoiceSelect','commentaryStatus','commentaryBtn','menuCommentaryBtn','commentaryTestBtn']){if(!ids[id])ids[id]=new El();}
for(const id of ['pauseMenu','pauseMatchInfo','pauseResume','pauseWatch','pauseFinish','pauseMainMenu','simReturn','simProgress'])ids[id]=new El();
for(const id of ['matchmakeBtn','cancelMatchmake','onlineStatus','onlineMatchBar'])ids[id]=new El();
for(const m of fs.readFileSync(require("path").join(__dirname,"../public/index.html"),"utf8").matchAll(/id="([^"]+)"/g))if(!ids[m[1]])ids[m[1]]=new El();
const context2d=new Proxy({createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>k in o?o[k]:(()=>{})});ids.game.getContext=()=>context2d;
const energy=new El('i');const store={};const errors=[];
const sandbox={console:{log:console.log,error:(...x)=>errors.push(x.join(' '))},performance:{now:()=>0},Math,Date,JSON,Number,String,Object,Array,Map,Set,Infinity,localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v},navigator:{getGamepads:()=>[]},screen:{},setTimeout:f=>f(),requestAnimationFrame:()=>{},document:{getElementById:id=>ids[id]||null,createElement:t=>new El(t),querySelector:s=>s==='#energy i'?energy:null,querySelectorAll:s=>s==='[data-tactic]'?all.filter(e=>e.dataset.tactic):all.filter(e=>e.dataset.mode),addEventListener(){},hidden:false},devicePixelRatio:1,addEventListener(){},confirm:()=>true};
sandbox.window=sandbox;sandbox.MINISAHA_BUNDLED_VOICE={};
let script=fs.readFileSync(require('path').join(__dirname,'../public/index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
script=script.replace(/\}\)\(\);\s*$/, 'window.inspect = code => eval(code);})();');
vm.createContext(sandbox);
for(const name of fs.readdirSync(require('path').join(__dirname,'../public/assets')).filter(n=>n.startsWith('rosters-')))vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../public/assets',name),'utf8'),sandbox);
vm.runInContext(script,sandbox);
const run=sandbox.inspect;
function test(name,f){f();console.log('PASS',name)}
function openPlay(){run("fullReset();startGame();setPiece=null;goalPause=0;ball.owner=null;ball.kicker=null;manualLock=0;clearInput();players.forEach((p,i)=>{p.x=100+i*30;p.y=100;p.vx=0;p.vy=0;p.cooldown=0;p.tackleCD=0;p.recoverTime=0;});selected=blue[1]");}
test('keeper action removed and defense mappings available',()=>{assert(!run("Object.keys(KEY_ACTIONS).includes('save')"));assert(run("KEY_ACTIONS.cross.includes('kayarak')"));});
test('buttons change immediately with possession',()=>{openPlay();run('ball.owner=red[1];updateHud()');assert.equal(ids.mPass.textContent,'PRES');assert.equal(ids.mCross.textContent,'KAY');run('ball.owner=blue[1];updateHud()');assert.equal(ids.mPass.textContent,'PAS');});
test('intended receiver selected while pass travels',()=>{openPlay();run("passAssist={team:'blue',target:blue[3]};updateAutoSelect(.016)");assert(run('selected===blue[3]'));});
test('manual selection protected and own carrier always controlled',()=>{openPlay();run("ball.owner=red[1];selected=blue[1];manualLock=1;blue[2].x=red[1].x-25;updateAutoSelect(.5)");assert(run('selected===blue[1]'));run('ball.owner=blue[3];updateAutoSelect(.016)');assert(run('selected===blue[3]'));});
test('directional prediction favors interception rather than current ball',()=>{openPlay();run("blue.slice(1).forEach(p=>{p.x=100;p.y=100});ball.x=400;ball.y=300;ball.vx=-300;ball.vy=0;ball.z=0;ball.vz=0;blue[1].x=450;blue[1].y=300;blue[2].x=310;blue[2].y=300");assert(run('selectionScore(blue[2])<selectionScore(blue[1])'));});
test('auto switch uses dwell and does not flicker',()=>{openPlay();run("ball.owner=red[1];red[1].x=500;red[1].y=300;blue[1].x=100;blue[1].y=100;blue[2].x=460;blue[2].y=300;updateAutoSelect(.1)");assert(run('selected===blue[1]'));run('updateAutoSelect(.1)');assert(run('selected===blue[2]'));run('blue[3].x=470;blue[3].y=300;updateAutoSelect(.1)');assert(run('selected===blue[2]'));});
test('holding press approaches carrier and joystick can override',()=>{openPlay();run('ball.owner=red[1];red[1].x=500;red[1].y=300;blue[1].x=300;blue[1].y=300');assert(run('handleDefense({passDown:true,x:0,y:0},.016).x>0'));assert.equal(run('handleDefense({passDown:true,x:-1,y:0},.016).x'),-1);});
test('second presser never goalkeeper and expires',()=>{openPlay();run('ball.owner=red[1];handleDefense({throughDown:true,x:0,y:0},.016)');assert(run("supportPresser&&supportPresser!==selected&&supportPresser.role!=='gk'"));run('for(let i=0;i<155;i++)handleDefense({throughDown:true},1/60)');assert(run('supportPressCooldown>0'));assert.equal(run('supportPresser'),null);});
test('standing tackle misses at distance and cooldown blocks spam',()=>{openPlay();run('ball.owner=red[1];ball.x=500;ball.y=300;selected.x=300;selected.y=300');assert(run('startDefensiveTackle(selected,false,{x:1,y:0})'));run('resolveDefensiveTackles()');assert(run('ball.owner===red[1]'));assert(!run('startDefensiveTackle(selected,false,{x:1,y:0})'));});
test('reachable exposed ball is poked without teleport or guaranteed possession',()=>{openPlay();run('selected.x=300;selected.y=300;red[1].x=330;red[1].y=310;ball.owner=red[1];ball.x=318;ball.y=300;startDefensiveTackle(selected,false,{x:1,y:0});resolveDefensiveTackles()');assert.equal(run('ball.owner'),null);assert.equal(run('ball.x'),318);assert.equal(run('stats.blue.tackles'),1);run('resolveDefensiveTackles()');assert.equal(run('stats.blue.tackles'),1);});
test('body between foot and ball blocks tackle',()=>{openPlay();run('selected.x=300;selected.y=300;red[1].x=313;red[1].y=300;ball.owner=red[1];ball.x=323;ball.y=300;startDefensiveTackle(selected,false,{x:1,y:0});resolveDefensiveTackles()');assert(run('ball.owner===red[1]'));});
test('slide has locked direction and recovery',()=>{openPlay();run('ball.owner=red[1];startDefensiveTackle(selected,true,{x:1,y:0})');assert(run('selected.slideTime>0'));const x=run('selected.vx');run('controlPlayer(selected,{x:-1,y:0,sprint:true},.1)');assert.equal(run('selected.vx'),x);run('for(let i=0;i<30;i++)updatePlayers(1/60)');assert.equal(run('selected.slideTime'),0);assert(run('selected.recoverTime>0'));});
test('defensive tap preserved between frames and cannot fire an attacking release',()=>{openPlay();run('ball.owner=red[1]');ids.mShoot.trigger('pointerdown');ids.mShoot.trigger('pointerup');run('window.quick=inputState(.016);handleDefense(quick,.016)');assert(run('selected.tackleCD>0'));run('ball.owner=selected;handleActions(quick,.016)');assert.equal(run('stats.blue.shots'),0);});
test('holding defense through turnover never charges a shot',()=>{openPlay();run('ball.owner=red[1];handleDefense({shootDown:true,shootPressed:true},.016);ball.owner=selected;handleActions({shootDown:true,shootPressed:true},.016)');assert.equal(run('kickCharge'),null);run('handleActions({shootReleased:true},.016)');assert.equal(run('stats.blue.shots'),0);});
test('restarts disable defending and clear slide',()=>{openPlay();run("selected.slideTime=.4;beginSetPiece('corner','blue',FIELD.r-24,FIELD.t+24);updateHud()");assert.equal(ids.mCross.textContent,'ORTA');assert(run('players.every(p=>p.slideTime===0)'));assert(!run('startDefensiveTackle(selected,true,{x:1,y:0})'));});
test('weak keepers weaker; both sides have identical model',()=>{openPlay();run('blue[0].roster={overall:60};red[0].roster={overall:60}');assert.equal(JSON.stringify(run('keeperSkills(blue[0])')),JSON.stringify(run('keeperSkills(red[0])')));run('red[0].roster={overall:90}');assert(run('keeperSkills(blue[0]).reaction>keeperSkills(red[0]).reaction'));assert(run('keeperSkills(red[0]).diveReach<53'));});
test('reset clears pressure and key latches',()=>{run('fullReset()');assert.equal(run('supportPresser'),null);assert(run('Object.values(defensiveLatch).every(x=>!x)'));});
test('5v5 and 11v11 game loops render without errors',()=>{for(const size of [5,11]){run(`matchSize=${size};fullReset();startGame();setPiece=null;ball.owner=red[3];mobile.pass=true;for(let i=0;i<900;i++){updateGame(1/60);if(i%120===0)render();}`);assert(run('players.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y))'));}assert.deepEqual(errors,[]);});
function keeperTrial(team,rating,offset){openPlay();run(`blue[0].roster={overall:${rating}};red[0].roster={overall:${rating}};players.forEach(p=>{if(p.role!=='gk'){p.x=FIELD.cx;p.y=FIELD.t+25;p.vx=0;p.vy=0;}});window.g='${team}'==='blue'?blue[0]:red[0];g.x=g.team==='blue'?FIELD.l+29:FIELD.r-29;g.y=GOAL.cy;g.aimY=GOAL.cy;g.vx=0;g.vy=0;g.diveTime=0;g.diveCooldown=0;g.trackingShot=false;ball.x=g.x+(g.team==='blue'?180:-180);ball.y=g.y+${offset};ball.vx=g.team==='blue'?-420:420;ball.vy=0;ball.z=0;ball.vz=0;ball.pickupDelay=0;ball.shotTeam=g.team==='blue'?'red':'blue';ball.shotOnTarget=true;ball.saveCounted=false;for(let i=0;i<60;i++){updateKeepers(1/60);updatePlayers(1/60);updateBallFree(1/60);}`);return run(`stats.${team}.saves`);}
test('keepers still save central real moving shots on both sides',()=>{for(const team of ['blue','red'])assert(keeperTrial(team,65,0)>0);});
test('physical keeper trials retain rating gap and cannot save unreachable shots',()=>{let weak=0,strong=0;for(const offset of [-65,-50,-35,-20,0,20,35,50,65]){weak+=keeperTrial('red',55,offset);strong+=keeperTrial('red',90,offset);}assert(strong>weak,`${strong} vs ${weak}`);assert.equal(keeperTrial('red',90,115),0);console.log('Keeper saves in 9 trajectories: low rating',weak,'high rating',strong);});
test('attacking pass still charges and releases after defensive button change',()=>{openPlay();run('ball.owner=blue[1];ball.x=blue[1].x;ball.y=blue[1].y;blue[1].cooldown=0;selected=blue[1];keys.KeyX=true;handleActions(inputState(.1),.1)');assert(run('kickCharge?.kind===\'pass\''));run('keys.KeyX=false;handleActions(inputState(.016),.016)');assert.equal(run('stats.blue.passes'),1);});
