const assert=require('node:assert/strict'),{run,ids,sandbox,errors}=require('./game-harness.cjs');
run("document.getElementById('leagueCareerMode').value='manager';document.getElementById('managerName').value='Akif';document.getElementById('leagueSelect').value='superlig';fillLeagueTeams();document.getElementById('leagueTeamSelect').value='superlig_fenerbahce';createLeagueSeason()");assert(run('validLeagueSeason(leagueSeason)'));assert.equal(run('leagueSeason.manager.name'),'Akif');assert.equal(ids.leagueTabTransfers.hidden,false);
const base=run('JSON.stringify(managerBaseRoster(leagueSeason.club))');run("leagueSeason.manager.balance=1000000000;leagueSeason.manager.wageLimit=10000000;document.getElementById('managerMarketClub').value='premier_manchestercity';renderManagerMarket();document.getElementById('managerMarketPlayer').value=managerRoster('premier_manchestercity').find(p=>p.name.includes('Haaland')).id");
const id=ids.managerMarketPlayer.value,cash=run('leagueSeason.manager.balance');run('managerBuy()');assert(run(`leagueSeason.manager.players.some(p=>p.id===${JSON.stringify(id)})`));assert(run('leagueSeason.manager.balance')<cash);assert(run(`!managerRoster('premier_manchestercity').some(p=>p.id===${JSON.stringify(id)})`));assert.equal(run('JSON.stringify(managerBaseRoster(leagueSeason.club))'),base);
ids.leagueTabTraining.trigger('click');ids.managerTrainingFocus.value='attack';ids.managerTrainingFocus.trigger('change');assert.equal(run('leagueSeason.manager.focus'),'attack');
const overall=run(`leagueSeason.manager.players.find(p=>p.id===${JSON.stringify(id)}).overall`);run(`leagueSeason.manager.development[${JSON.stringify(id)}]=90;playNextLeagueMatch()`);assert(run(`blue.some(p=>p.roster.id===${JSON.stringify(id)})`));assert(run('managerRosterScope'));run('score.blue=2;score.red=0;endMatch()');assert.equal(run('leagueSeason.round'),1);assert.equal(run(`leagueSeason.manager.players.find(p=>p.id===${JSON.stringify(id)}).overall`),overall+1);assert.equal(run('leagueSeason.manager.trust'),72);
// Reload, save slots, goal reset, restart and pause substitutions keep transferred players.
run('fullReset();readLeagueSlots();playNextLeagueMatch()');assert(run(`blue.some(p=>p.roster.id===${JSON.stringify(id)})`));ids.restartBtn.trigger('click');assert(run(`blue.some(p=>p.roster.id===${JSON.stringify(id)})`));run('resetKickoff();togglePause();renderSubstitutions()');assert(run(`blue.some(p=>p.roster.id===${JSON.stringify(id)})`));run('fullReset();startGame()');assert(!run('managerRosterScope'));assert(!run(`rosterFor('superlig_fenerbahce').some(p=>p.id===${JSON.stringify(id)})`));run('fullReset()');
// Renewals debit bonus, increase wage and persist the contract.
run(`document.getElementById('managerContractPlayer').value=${JSON.stringify(id)};managerRenew()`);assert.equal(run(`leagueSeason.manager.contracts[${JSON.stringify(id)}].years`),3);assert(run('validLeagueSeason(leagueSeason)'));
const count=run('leagueSeason.manager.players.length');ids.managerSellPlayer.value=id;ids.managerMarketClub.value='premier_liverpool';ids.managerSellBtn.trigger('click');assert.equal(run('leagueSeason.manager.players.length'),count-1);assert(run(`managerRoster('premier_liverpool').some(p=>p.id===${JSON.stringify(id)})`));
// Out-of-window buys, insufficient budget and duplicate ownership cannot alter the squad.
run("leagueSeason.round=8;leagueSeason.manager.balance=0;document.getElementById('managerMarketClub').value='premier_arsenal';renderManagerMarket();managerBuy()");assert.equal(run('leagueSeason.manager.players.length'),count-1);run('leagueSeason.round=0;managerBuy()');assert.equal(run('leagueSeason.manager.players.length'),count-1);assert.match(ids.managerActionStatus.textContent,/yetersiz/);
// Persisted records are independent from unsaved mutations.
run('readLeagueSlots()');const saved=run('JSON.stringify(leagueSlots[activeLeagueSlot].season.manager)');run('leagueSeason.manager.trust=1');assert.equal(run('JSON.stringify(leagueSlots[activeLeagueSlot].season.manager)'),saved);run('readLeagueSlots()');
// Season transition carries manager, finances, squad and contracts into a new year.
run('for(const d of [leagueSeason,leagueSeason.partner]){for(const week of d.fixtures)for(const m of week){m.homeGoals=1;m.awayGoals=0;}d.round=d.fixtures.length;}finishLeagueSeason();saveLeague();advanceLeagueSeason()');assert.equal(run('leagueSeason.season'),'2027–28');assert.equal(run('leagueSeason.manager.name'),'Akif');assert(run('validLeagueSeason(leagueSeason)'));assert.equal(run('leagueSeason.manager.history.length'),0);
// Complete a real manager season week by week: charges/development and board results once.
while(run('leagueSeason.round<leagueSeason.fixtures.length')){run('playNextLeagueMatch();score.blue=2;score.red=0;endMatch()');assert(run('validLeagueSeason(leagueSeason)'));}
assert.equal(run('leagueSeason.manager.history.length'),1);assert(run('leagueSeason.manager.history[0].met'));run('advanceLeagueSeason()');assert(run('validLeagueSeason(leagueSeason)'));assert(run('leagueSeason.manager.players.length>=11&&leagueSeason.manager.players.some(p=>p.positions.includes("GK"))'));
run("MINISAHA_ENGINE.boot({blue:'superlig_fenerbahce',red:'premier_liverpool',size:11})");assert(!run('managerRosterScope'));assert.equal(run('JSON.stringify(managerBaseRoster(leagueSeason.club))'),run('JSON.stringify(rosterFor(leagueSeason.club))'));
assert(run('(()=>{const s=JSON.parse(JSON.stringify(leagueSeason));s.manager.players=[];return !validLeagueSeason(s)})()'));assert.deepEqual(errors,[]);console.log('PASS manager creation, buy/sell roster ownership, actual match/restart/substitution persistence, normal-match isolation, training, wages/contracts, slot reload/copy isolation, season continuation, invalid budgets/window/save protection');
