// Compatibility client for integration tests on Node 18/20 (no npm dependency).
const net=require('node:net'),crypto=require('node:crypto');
module.exports=class SocketClient{
 constructor(address){const url=new URL(address);this.listeners={};this.readyState=0;this.buffer=Buffer.alloc(0);this.socket=net.connect(Number(url.port)||80,url.hostname,()=>{const key=crypto.randomBytes(16).toString('base64');this.accept=crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');this.socket.write('GET '+url.pathname+url.search+' HTTP/1.1\r\nHost: '+url.host+'\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: '+key+'\r\n\r\n');});this.socket.on('error',e=>this.emit('error',e));this.socket.on('close',()=>{this.readyState=3;this.emit('close',{});});this.socket.on('data',chunk=>{this.buffer=Buffer.concat([this.buffer,chunk]);if(this.readyState===0){const at=this.buffer.indexOf('\r\n\r\n');if(at<0)return;const headers=this.buffer.subarray(0,at).toString();if(!headers.startsWith('HTTP/1.1 101')||!headers.includes(this.accept)){this.emit('error',new Error('upgrade failed'));this.socket.destroy();return;}this.buffer=this.buffer.subarray(at+4);this.readyState=1;this.emit('open',{});}while(this.buffer.length>=2){const op=this.buffer[0]&15;let n=this.buffer[1]&127,offset=2;if(n===126){if(this.buffer.length<4)return;n=this.buffer.readUInt16BE(2);offset=4;}if(this.buffer.length<offset+n)return;const payload=this.buffer.subarray(offset,offset+n);this.buffer=this.buffer.subarray(offset+n);if(op===1)this.emit('message',{data:payload.toString()});else if(op===8){this.socket.end();return;}}});}
 addEventListener(type,fn,options){(this.listeners[type]??=[]).push({fn,once:options?.once});}
 emit(type,event){const items=[...(this.listeners[type]||[])];this.listeners[type]=(this.listeners[type]||[]).filter(x=>!x.once);for(const {fn}of items)fn(event);}
 frame(op,text){const data=Buffer.from(text),mask=crypto.randomBytes(4),header=Buffer.alloc(data.length<126?2:4);header[0]=0x80|op;if(data.length<126)header[1]=128|data.length;else{header[1]=128|126;header.writeUInt16BE(data.length,2);}for(let i=0;i<data.length;i++)data[i]^=mask[i%4];this.socket.write(Buffer.concat([header,mask,data]));}
 send(text){this.frame(1,text);}
 close(){if(this.readyState===1)this.frame(8,'');this.socket.end();}
};
