"""Build offline squads from reviewed snapshots; FC26 data supplies attributes only.
Usage: python3 tools/build_rosters.py /path/to/players.csv
The CSV URL and digest are recorded in roster-source/manifest.json.
"""
import sys,json,csv,pathlib,collections,unicodedata,re,hashlib,statistics
ROOT=pathlib.Path(__file__).resolve().parents[1]
def norm(s):return re.sub('[^a-z0-9]','',unicodedata.normalize('NFKD',s.lower().replace('ı','i')).encode('ascii','ignore').decode())
def number(value,default):
 try:return round(float(value))
 except (ValueError,TypeError):return default
ratings=pathlib.Path(sys.argv[1]);bydob=collections.defaultdict(list)
for r in csv.DictReader(ratings.open()):bydob[r['dob']].append(r)
def match(a):
 dob=(a.get('dateOfBirth') or '')[:10]
 if not dob:return None
 names=[norm(a.get(k) or '') for k in ['displayName','fullName','shortName','lastName']]
 found=[r for r in bydob[dob] if any(x and (x==norm(r['short_name']) or x==norm(r['long_name']) or (len(x)>4 and x in norm(r['long_name']))) for x in names)]
 return found[0] if len(found)==1 else None
posmap={'CDM':'DM','CAM':'AM','CF':'AM','LWB':'LB','RWB':'RB'}
counts=collections.Counter();manifest={'date':'2026-09-28','rosterSeason':'2026–27 clubs / 2026 national teams','ratingSource':'https://raw.githubusercontent.com/ismailoksuz/EAFC26-DataHub/main/data/players.csv','ratingSourceSHA256':hashlib.sha256(ratings.read_bytes()).hexdigest(),'ratingEdition':'FC26, update 2025-09-19; not official FC27','estimatedRatings':'Unmatched players use explicitly labelled gameplay estimates, not EA ratings.','teams':{}}
htmlPath=ROOT/'public/index.html';html=htmlPath.read_text()
for file in sorted((ROOT/'roster-source').glob('*.json')):
 if file.name=='manifest.json':continue
 if file.name=='lower.json':
  # Reviewed lower-tier asset preserves its team catalogue and ID-reused ratings.
  prior=json.loads((ROOT/'roster-source/manifest.json').read_text())
  asset=ROOT/'public/assets'/prior['lowerAsset']
  raw=asset.read_text().split('window.MINISAHA_ROSTERS||{},',1)[1].split(');\nwindow.MINISAHA_LOWER_TEAMS=',1)[0]
  for key,t in json.loads(raw).items():
   manifest['teams'][key]=prior['teams'][key]
   counts.update(p['ratingSource'] for p in t['players'])
  manifest['lowerAsset']=prior['lowerAsset'];manifest['lowerScope']=prior['lowerScope']
  continue
 data=json.loads(file.read_text());out={}
 for key,t in data.items():
  pairs=[(a,match(a)) for a in t['players']];known=[int(r['overall']) for a,r in pairs if r];base=round(statistics.median(known)) if known else 66
  cards=[]
  for a,r in pairs:
   name=a['displayName'];positions=[posmap.get(p.strip(),p.strip()) for p in r['player_positions'].split(',')] if r else [{'G':'GK'}.get(a['position'],a['position'])]
   if not r and a['position']=='G':positions=['GK']
   if r:
    canonical={norm(token):token for token in r['long_name'].split() if all(not c.isalpha() or 'LATIN' in unicodedata.name(c,'') for c in token)}
    name=' '.join(canonical.get(norm(token),token) for token in name.split())
   age=2026-int((a.get('dateOfBirth') or '2000')[:4]);estimate=max(52,min(76,base-(8 if age<21 else 3)))
   overall=int(r['overall']) if r else estimate
   card={'id':a['id'],'name':name,'position':positions[0],'positions':positions,'jersey':a['jersey'],'overall':overall,'ratingSource':'FC26' if r else 'estimate'}
   metrics={'pace':'pace','shot':'shooting','pass':'passing','tackle':'defending','dribble':'dribbling','physical':'physic','strength':'power_strength','jumping':'power_jumping','finishing':'attacking_finishing'}
   for prop,col in metrics.items():
    fallback=overall
    if a['position']=='G' and prop in ['shot','finishing','tackle']:fallback=35
    if a['position']=='D' and prop in ['shot','finishing']:fallback=max(35,overall-18)
    if a['position']=='F' and prop=='tackle':fallback=max(35,overall-22)
    card[prop]=number(r.get(col),fallback) if r else fallback
   if r:card['ratingId']=r['player_id']
   cards.append(card);counts[card['ratingSource']]+=1
  assert len({c['id'] for c in cards})==len(cards),key
  assert len(cards)>=11 and any(c['position']=='GK' for c in cards),key
  out[key]={'season':t['season'],'updated':'28.09.2026','players':cards}
  manifest['teams'][key]={k:v for k,v in t.items() if k!='players'}|{'players':len(cards),'fc26Matched':sum(c['ratingSource']=='FC26' for c in cards)}
 text='// Generated by tools/build_rosters.py. Reviewed source snapshots: roster-source/.\nObject.assign(window.MINISAHA_ROSTERS ||= {},'+json.dumps(out,ensure_ascii=False,separators=(',',':'))+');\n'
 asset=f'rosters-{file.stem}-{hashlib.sha256(text.encode()).hexdigest()[:10]}.js'
 for old in (ROOT/'public/assets').glob(f'rosters-{file.stem}*.js'):old.unlink()
 (ROOT/'public/assets'/asset).write_text(text)
 html=re.sub(r'assets/rosters-'+file.stem+r'(?:-[a-f0-9]+)?\.js(?:\?[^\"]*)?', 'assets/'+asset, html)
manifest['counts']={'teams':len(manifest['teams']),'players':sum(counts.values()),**counts}
(ROOT/'roster-source/manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
htmlPath.write_text(html)
print(manifest['counts'])
